---

- name: Install dependencies
  apt: name=supervisor update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install superlance
  pip: name=superlance
  when: supervisor_superlance

- name: Prepare directories
  file: state=directory path={{item}}
  with_items:
    - "{{supervisor_cfgdir}}"
    - "{{supervisor_logdir}}"
    - "{{supervisor_incdir}}"

- name: Configure supervisor - pt. 1
  template: src=supervisord.conf.j2 dest={{supervisor_conf_file}} owner=root group=root mode=0644
  notify:
    - supervisor restart

- name: Configure supervisor - pt. 2
  template: src=supervisor.conf.j2 dest=/etc/init/supervisor.conf owner=root group=root mode=0755

- name: Ensure the supervisor is started
  service: name=supervisor state=started
